# Use postgres/example user/password credentials
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    restart: unless-stopped
    image: adminer
    ports:
      - 8081:8080

volumes:
  postgres_data:
